/// Golden Rules enforcement tests — generated by spine-rules.
use spine_rules::golden_rules_suite;

golden_rules_suite! {
    binary: env!("CARGO_BIN_EXE_pack"),
    operator_json: include_str!("../operator.json"),
    source_files: &[
        "src/refusal/codes.rs",
        "src/operator.rs",
        "src/verify/command.rs",
    ],
    fixture_success_args: &[
        "verify",
        "fixtures/packs/valid",
        "--json", "--no-witness",
    ],
    fixture_refusal_args: &[
        "verify",
        "/nonexistent/pack",
        "--json", "--no-witness",
    ],
}
